<?php header("Access-Control-Allow-Origin:*");header('Access-Control-Max-Age:86400');header('Content-Type:application/json');
header("Access-Control-Allow-Methods:GET");if(isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])){header("Access-Control-Allow-Headers:{$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");}
$response=new stdClass;
$rules=array();
$rule=new stdClass;
// ***************************************************************
$rule=new stdClass;
$rule->pathPattern = "/mcswap";
$rule->apiPath = "https://www.solana-action-express.com/mcswap";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/spl/*";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-spl-config/*";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/swap-nft/*";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-nft-config/*";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/swap-pnft/*";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-pnft-config/*";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/swap-cnft/*";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-cnft-config/*";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/swap-core/*";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-core-config/*";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/createSPL";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-spl-create";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/createNFT";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-nft-create";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/createPNFT";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-pnft-create";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/createCNFT";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-cnft-create";
$rules[] = $rule;
$rule=new stdClass;
$rule->pathPattern = "/createCORE";
$rule->apiPath = "https://www.solana-action-express.com/mcswap-core-create";
$rules[] = $rule;
// ***************************************************************
$response->rules=$rules;
echo json_encode($response);
exit();